name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 🔥 Permission khusus untuk GITHUB_TOKEN
    permissions:
      contents: write  # Untuk push ke branch
      pages: write     # Khusus GitHub Pages
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node 23
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build project
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          # Add these new settings:
          full_commit_message: "Deploy to GitHub Pages (via GitHub Actions)"
          force_orphan: true
          keep_files: false
